import { useEffect, useState } from "react";
import { useGame, type Popup } from "../../game/store";
import { KICK, KICK_FIELD } from "./kickState";

const tones: Record<Popup["tone"], string> = { gold: "#ffd23e", cyan: "#38d6d0", red: "#ff6b5e", green: "#57d977", purple: "#b58cff", white: "#f2f4f8" };
function Score() { const [v, setV] = useState({ runs: 0, outs: 0, inning: 1, phase: "ready" }); useEffect(() => { const id = window.setInterval(() => { const t = KICK.current; setV({ runs: t.runs, outs: t.outs, inning: t.inning, phase: t.phase }); }, 80); return () => window.clearInterval(id); }, []); return <div className="pointer-events-none absolute left-5 top-5 rounded-2xl border border-white/15 bg-[#0d1219]/82 px-5 py-3 backdrop-blur-sm"><div className="flex items-end gap-7"><div><div className="text-[9px] font-extrabold tracking-[0.3em] text-[#ffd23e]">RUNS</div><div className="font-display text-4xl leading-none text-[#ffd23e]">{v.runs}<span className="ml-1 text-lg text-white/35">/ {KICK_FIELD.winRuns}</span></div></div><div><div className="text-[9px] font-extrabold tracking-[0.25em] text-[#ff6b5e]">OUTS</div><div className="font-display text-2xl leading-none text-[#ff8a7a]">{v.outs} / {KICK_FIELD.maxOuts}</div></div><div><div className="text-[9px] font-extrabold tracking-[0.2em] text-white/35">INNING</div><div className="font-display text-2xl leading-none text-white/80">{v.inning}</div></div></div></div>; }
function Banner() { const [b, setB] = useState({ text: "", at: -99 }); useEffect(() => { const id = window.setInterval(() => { const t = KICK.current; if (t.bannerAt !== b.at) setB({ text: t.banner, at: t.bannerAt }); }, 80); return () => window.clearInterval(id); }, [b.at]); if (!b.text) return null; return <div className="pointer-events-none absolute left-1/2 top-[28%] -translate-x-1/2 rounded-2xl border-2 border-[#ff8a7a] bg-[#10141c]/88 px-8 py-4 text-center backdrop-blur-sm"><div className="animate-bannerin font-display text-3xl text-[#ff8a7a]">{b.text}</div></div>; }
function Popups() { const popups = useGame((s) => s.popups); return <div className="pointer-events-none absolute inset-0 flex items-start justify-center pt-[38%]"><div className="flex flex-col-reverse items-center gap-1">{popups.slice(-3).map((p) => <div key={p.id} className="animate-popfont font-display text-center leading-none" style={{ color: tones[p.tone], fontSize: p.big ? 34 : 23, textShadow: "0 3px 0 rgba(0,0,0,0.5)" }}>{p.text}</div>)}</div></div>; }
function Settings() { const muted = useGame((s) => s.muted); const toggle = useGame((s) => s.toggleMute); const toMenu = useGame((s) => s.toMenu); const [open, setOpen] = useState(false); return <div className="pointer-events-auto absolute right-5 top-5 flex gap-2"><button onClick={toggle} className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/15 bg-[#0d1219]/80 text-lg backdrop-blur-sm">{muted ? "🔇" : "🔊"}</button><button onClick={() => setOpen((x) => !x)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/15 bg-[#0d1219]/80 text-lg backdrop-blur-sm">⚙️</button>{open && <div className="absolute right-0 top-12 w-72 rounded-2xl border border-white/15 bg-[#0d1219]/95 p-4 backdrop-blur-md"><div className="mb-2 font-display text-xs tracking-[0.25em] text-white/70">KICKBALL RULEBOOK</div><div className="space-y-1.5 text-[11px] font-bold text-white/60"><div>◈ SPACE or CLICK — kick the rolling pitch</div><div>◈ WASD — move and chase the ball</div><div>◈ Reach base before the fielders get the ball</div><div>◈ First to {KICK_FIELD.winRuns} runs wins; three outs resets the inning</div></div><button onClick={() => { setOpen(false); toMenu(); }} className="mt-3 w-full rounded-xl bg-white/10 py-2 text-xs font-bold text-white/65">BACK TO PLAYGROUND</button></div>}</div>; }
export function KickHUD() { return <div className="pointer-events-none absolute inset-0 z-10 font-body"><Score /><Settings /><Banner /><Popups /><div className="pointer-events-none absolute bottom-5 left-1/2 -translate-x-1/2 rounded-full bg-[#10141c]/65 px-5 py-2 text-[11px] font-bold tracking-[0.16em] text-white/55 backdrop-blur-sm">WASD RUN · SPACE / CLICK KICK · FIRST TO {KICK_FIELD.winRuns}</div></div>; }
